---
- include: install.yml
  sudo: true
  tags: 
    - openldap
    - install

- include: configure.yml
  sudo: true
  tags: 
    - openldap
    - configure

- include: pam.yml
  sudo: true
  tags:
    - openldap
    - pam
